### ISSUE TITLE
The complete code and demos for training/evaluating

### ISSUE THREAD

**Issue by yzhang-gh** [jiang-yuan/Learning-routing-DRO#1]
Thanks for your paper "Learning to Solve Routing Problems via Distributionally Robust Optimization", which is an interesting direction.

However, could you please double-check the provided source code?

For example, there doesn't seem to be any `data.data` module in this repository, or is it a dependency?
https://github.com/jiang-yuan/Learning-routing-DRO/blob/main/run.py#L9

Also, it would be much more helpful if you can provide a few demos for reproducing the training/evaluating processes in the paper (currently there is only a `python3 run.py`).

**Comment by jiang-yuan** [comment]
Ok. I am busy recently. I will double-check and update the code at the end of this month.
